/* Generated by Yosys 0.69+ (git sha1 4d572059c, Release, GNU /usr/bin/c++ 13.3.0) [github.com/vibeic/yosys at HEAD] */

module cal_bmc_init(clk, rst, go, tap, busy);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input go;
  wire go;
  output tap;
  wire tap;
  output busy;
  wire busy;
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire [7:0] lfsr;
  wire [1:0] st;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _06_ (
    .I(st[0]),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _07_ (
    .A1(_03_),
    .A2(st[1]),
    .ZN(busy)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _08_ (
    .A1(st[0]),
    .A2(st[1]),
    .Z(_02_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _09_ (
    .A1(st[1]),
    .A2(go),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _10_ (
    .A1(st[0]),
    .A2(_04_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _11_ (
    .A1(lfsr[4]),
    .A2(lfsr[3]),
    .Z(_05_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _12_ (
    .A1(lfsr[7]),
    .A2(lfsr[5]),
    .A3(_05_),
    .Z(_00_[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _13_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(lfsr[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _14_ (
    .CLK(clk),
    .D(lfsr[0]),
    .Q(lfsr[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _15_ (
    .CLK(clk),
    .D(lfsr[1]),
    .Q(lfsr[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _16_ (
    .CLK(clk),
    .D(lfsr[2]),
    .Q(lfsr[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _17_ (
    .CLK(clk),
    .D(lfsr[3]),
    .Q(lfsr[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _18_ (
    .CLK(clk),
    .D(lfsr[4]),
    .Q(lfsr[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _19_ (
    .CLK(clk),
    .D(lfsr[5]),
    .Q(lfsr[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _20_ (
    .CLK(clk),
    .D(lfsr[6]),
    .Q(lfsr[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _21_ (
    .CLK(clk),
    .D(_02_),
    .Q(st[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _22_ (
    .CLK(clk),
    .D(_01_),
    .Q(st[0])
  );
  assign _00_[7:1] = lfsr[6:0];
  assign tap = lfsr[0];
endmodule
