/* Generated by Yosys 0.69+ (git sha1 4d572059c, Release, GNU /usr/bin/c++ 13.3.0) [github.com/vibeic/yosys at HEAD] */

module cal_bmc(clk, rst, en, q, hit);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input en;
  wire en;
  output [3:0] q;
  wire [3:0] q;
  output hit;
  wire hit;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _15_ (
    .I(rst),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _16_ (
    .I(q[2]),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _17_ (
    .A1(q[2]),
    .A2(q[0]),
    .A3(q[1]),
    .A4(en),
    .Z(_12_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _18_ (
    .A1(q[3]),
    .A2(_12_),
    .ZN(_13_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _19_ (
    .A1(rst),
    .A2(_13_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _20_ (
    .A1(q[2]),
    .A2(_07_),
    .B(_05_),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _21_ (
    .A1(_12_),
    .A2(_14_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _22_ (
    .A1(q[0]),
    .A2(q[1]),
    .A3(en),
    .Z(_07_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _23_ (
    .A1(q[0]),
    .A2(en),
    .B(q[1]),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _24_ (
    .A1(rst),
    .A2(_07_),
    .A3(_08_),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _25_ (
    .A1(q[0]),
    .A2(en),
    .B(_05_),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _26_ (
    .A1(q[0]),
    .A2(en),
    .B(_09_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _27_ (
    .A1(q[2]),
    .A2(q[3]),
    .A3(q[0]),
    .A4(q[1]),
    .Z(_10_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _28_ (
    .A1(en),
    .A2(hit),
    .B(_05_),
    .ZN(_11_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _29_ (
    .A1(en),
    .A2(_10_),
    .B(_11_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _30_ (
    .CLK(clk),
    .D(_00_),
    .Q(q[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _31_ (
    .CLK(clk),
    .D(_01_),
    .Q(q[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _32_ (
    .CLK(clk),
    .D(_02_),
    .Q(hit)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _33_ (
    .CLK(clk),
    .D(_03_),
    .Q(q[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _34_ (
    .CLK(clk),
    .D(_04_),
    .Q(q[1])
  );
endmodule
