/* Generated by Yosys 0.69+ (git sha1 4d572059c, Release, GNU /usr/bin/c++ 13.3.0) [github.com/vibeic/yosys at HEAD] */

module cal_bmc_pdx(clk, rst, go, abort, notrun, done);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input go;
  wire go;
  input abort;
  wire abort;
  output notrun;
  wire notrun;
  output done;
  wire done;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire rst_q;
  wire [3:0] st;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _09_ (
    .I(st[2]),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _10_ (
    .A1(rst_q),
    .A2(_04_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _11_ (
    .A1(rst_q),
    .A2(abort),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _12_ (
    .A1(st[0]),
    .A2(_05_),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _13_ (
    .A1(go),
    .A2(st[0]),
    .A3(_05_),
    .Z(_01_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _14_ (
    .A1(st[0]),
    .A2(st[1]),
    .B(abort),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _15_ (
    .A1(rst_q),
    .A2(st[3]),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or3_1 _16_ (
    .A1(st[0]),
    .A2(st[3]),
    .A3(st[1]),
    .Z(notrun)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _17_ (
    .A1(go),
    .A2(_06_),
    .B(_07_),
    .C(_08_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _18_ (
    .A1(st[1]),
    .A2(_05_),
    .Z(_02_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _19_ (
    .CLK(clk),
    .D(_03_),
    .Q(st[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _20_ (
    .CLK(clk),
    .D(_00_),
    .Q(st[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _21_ (
    .CLK(clk),
    .D(_01_),
    .Q(st[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _22_ (
    .CLK(clk),
    .D(_02_),
    .Q(st[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _23_ (
    .CLK(clk),
    .D(rst),
    .Q(rst_q)
  );
  assign done = st[1];
endmodule
