/* Generated by Yosys 0.69+ (git sha1 4d572059c, Release, GNU /usr/bin/c++ 13.3.0) [github.com/vibeic/yosys at HEAD] */

module cal_bmc_rsync(clk, rst, go, ready, busy);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input go;
  wire go;
  output ready;
  wire ready;
  output busy;
  wire busy;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire rst_s1;
  wire rst_s2;
  wire [3:0] st;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _09_ (
    .I(st[1]),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _10_ (
    .I(st[2]),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _11_ (
    .I(st[0]),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _12_ (
    .A1(_04_),
    .A2(rst_s2),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _13_ (
    .A1(rst_s2),
    .A2(_05_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _14_ (
    .A1(st[0]),
    .A2(go),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _15_ (
    .A1(rst_s2),
    .A2(_07_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _16_ (
    .A1(rst_s2),
    .A2(st[3]),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _17_ (
    .A1(_06_),
    .A2(go),
    .B(_08_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _18_ (
    .CLK(clk),
    .D(_03_),
    .Q(st[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _19_ (
    .CLK(clk),
    .D(_00_),
    .Q(st[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _20_ (
    .CLK(clk),
    .D(_01_),
    .Q(st[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _21_ (
    .CLK(clk),
    .D(_02_),
    .Q(st[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _22_ (
    .CLK(clk),
    .D(rst),
    .Q(rst_s1)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _23_ (
    .CLK(clk),
    .D(rst_s1),
    .Q(rst_s2)
  );
  assign busy = st[2];
  assign ready = st[0];
endmodule
