/* Generated by Yosys 0.69+ (git sha1 4d572059c, Release, GNU /usr/bin/c++ 13.3.0) [github.com/vibeic/yosys at HEAD] */

module cal_bmc_xdc(clk, rst, sel, a, b, c, y);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [1:0] sel;
  wire [1:0] sel;
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output y;
  wire y;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _07_ (
    .I(a),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _08_ (
    .I(sel[0]),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _09_ (
    .A1(_06_),
    .A2(sel[1]),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _10_ (
    .A1(_06_),
    .A2(sel[1]),
    .Z(_02_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or3_1 _11_ (
    .A1(_05_),
    .A2(_01_),
    .A3(_02_),
    .Z(_03_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _12_ (
    .A1(b),
    .A2(_01_),
    .B1(_02_),
    .B2(c),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _13_ (
    .A1(_03_),
    .A2(_04_),
    .B(rst),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _14_ (
    .CLK(clk),
    .D(_00_),
    .Q(y)
  );
endmodule
