/* Generated by Yosys 0.69+ (git sha1 143146510, Release, GNU /usr/bin/c++ 13.3.0) [github.com/vibeic/yosys at HEAD] */

module neutral(sig, \a//b );
  input sig;
  wire sig;
  output [1:0] \a//b ;
  wire [1:0] \a//b ;
  assign \a//b  = { sig, 1'hx };
endmodule
