/* Generated by Yosys 0.69+ (git sha1 4d572059c, Release, GNU /usr/bin/c++ 13.3.0) [github.com/vibeic/yosys at HEAD] */

module cal_const(clk, a, y, hi, lo);
  input clk;
  wire clk;
  input a;
  wire a;
  output y;
  wire y;
  output hi;
  wire hi;
  output lo;
  wire lo;
  wire _0_;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _1_ (
    .I(a),
    .ZN(_0_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(y)
  );
  assign lo = 1'h0;
  assign hi = 1'h1;
endmodule
