#!/usr/bin/env python3
"""#2347: this file is an ES module, so a bare `require()` in it is a
ReferenceError — not at load time, but on the first call that reaches one.

``package.json`` declares ``"type": "module"`` and ``index.js`` opens with 27
top-level ``import`` statements, yet five call sites reached for CommonJS
``require``.  In an ESM scope that identifier does not exist, so every tool
routed through one of them answered ``require is not defined`` — for any input,
on every invocation.

WHY IT SURVIVED 400+ COMMITS.  Nothing in ``mcp-eda/test/`` sends a real
``tools/call``: the liveness and doctor tests probe the container and the
process, and the inventory tests assert that 56 tools are REGISTERED.  A tool
that throws on every call is registered.  Registration and invocability are
different facts and only the first had a test.

TWO OF THE EIGHT AFFECTED TOOLS FAILED SILENTLY, which is why the rule below is
pinned instead of just the four loud ones:

  * ``canonicalizeNetlistSrcCoords`` is wrapped in ``catch (_e) { return false; }``.
    It returned false on every call, so yosys's ``<abs-path>:<line>``
    autogenerated names were never canonicalized — the one thing the function
    exists for — and ``eda_synth`` reported success throughout.
  * ``eda_workflow_run`` swallows the throw in ``catch (e) { allOk = false; }``
    and returns a ``manifest_path`` for a file it never wrote.

So this file pins the RULE, not the four symptoms: in an ESM module, any
``require(`` obliges a ``createRequire`` binding.  A symptom test would go
green again the moment someone adds a sixth site.
"""
import json
import re
import shutil
import subprocess
from pathlib import Path

import pytest

SRC = Path(__file__).resolve().parent.parent / "src"
INDEX_JS = SRC / "index.js"
PKG_JSON = SRC.parent / "package.json"
assert INDEX_JS.exists()
NODE = shutil.which("node")

#: `require` as a CALL, not the word inside `required` or a comment's prose.
_REQUIRE_CALL = re.compile(r"(?<![\w.$])require\s*\(")


def _strip_comments(js: str) -> str:
    """Blank out // and /* */ comments, leaving string and template literals
    intact.

    LOAD-BEARING. Without it a comment reading "we should use createRequire one
    day" satisfies every assertion below, and this file goes green against a
    source that still throws on every call. Measured: a comment-only edit
    turned 2 of these 3 tests green before this was added.
    """
    out, i, n = [], 0, len(js)
    quote = None            # ' " ` when inside a literal
    while i < n:
        c, nxt = js[i], js[i + 1] if i + 1 < n else ""
        if quote:
            if c == "\\":
                out.append("  "); i += 2; continue
            if c == quote:
                quote = None
            out.append(c); i += 1; continue
        if c in "'\"`":
            quote = c; out.append(c); i += 1; continue
        if c == "/" and nxt == "/":
            while i < n and js[i] != "\n":
                out.append(" "); i += 1
            continue
        if c == "/" and nxt == "*":
            while i < n and not (js[i] == "*" and i + 1 < n and js[i + 1] == "/"):
                out.append("\n" if js[i] == "\n" else " "); i += 1
            out.append("  "); i += 2; continue
        out.append(c); i += 1
    return "".join(out)


def test_an_esm_module_that_calls_require_must_define_it():
    """The rule. Pure Python: a node-gated arm would SKIP where node is absent
    and hand back the same green as a pass."""
    if json.loads(PKG_JSON.read_text()).get("type") != "module":
        pytest.skip("not an ES module; the bare-require rule does not apply")
    code = _strip_comments(INDEX_JS.read_text())
    calls = _REQUIRE_CALL.findall(code)
    if not calls:
        return
    assert re.search(r"const\s+require\s*=\s*createRequire\(", code), (
        f"index.js is an ES module and calls require() at {len(calls)} site(s) "
        "(comments stripped), but no `const require = createRequire(...)` "
        "binding exists in CODE. Every tool reaching one of those sites throws "
        "'require is not defined'.")


def test_the_binding_is_anchored_to_this_module():
    code = _strip_comments(INDEX_JS.read_text())
    if not _REQUIRE_CALL.search(code):
        pytest.skip("no require() calls to anchor")
    assert re.search(
        r'import\s*\{\s*createRequire\s*\}\s*from\s*"node:module"', code), \
        "createRequire must be imported from node:module"
    assert re.search(
        r"const\s+require\s*=\s*createRequire\(\s*import\.meta\.url\s*\)", code), \
        "the resolver must be anchored at this module's own URL"


@pytest.mark.skipif(NODE is None, reason="node not available")
def test_a_helper_that_calls_require_actually_runs():
    """The behavioural half, extracted from index.js and run under node — so a
    revert reddens this rather than leaving a comment behind.

    `_runPyProgram` is the densest of the five sites: its first three
    statements are unconditional require()s, and four registered tools
    (eda_fpga_gds_reverify, eda_fpga_gate_attestation_check,
    eda_chip_top_gate_wrapper_gen, eda_rtl_name_semantic_check) each call it.
    """
    src = INDEX_JS.read_text()
    a = src.index("function _runPyProgram(")
    fn = src[a: src.index("\n}\n", a) + 3]
    # THE PRELUDE IS THE PRODUCT'S, NOT OURS. Injecting a createRequire here
    # would test the harness: an earlier draft did exactly that, keyed on the
    # STRING appearing anywhere in the file, and a comment-only edit turned this
    # green. Take the real binding lines out of index.js, or take nothing.
    code = _strip_comments(src)
    prelude = ""
    for pat in (r'import\s*\{\s*createRequire\s*\}\s*from\s*"node:module";',
                r"const\s+require\s*=\s*createRequire\(\s*import\.meta\.url\s*\);"):
        m = re.search(pat, code)
        if m:
            prelude += m.group(0) + "\n"
    # Drive the REAL function with only its filesystem probe stubbed, so the
    # require()s themselves are exercised.
    js = (prelude + "const existsSync = () => false;\n" + fn + "\n"
          'try { _runPyProgram("x.py", ["a"]); console.log("RAN"); }\n'
          'catch (e) { console.log("THREW:" + e.message); }\n')
    r = subprocess.run([NODE, "--input-type=module", "-e", js],
                       capture_output=True, text=True, timeout=60)
    assert r.returncode == 0, r.stderr
    out = r.stdout.strip()
    assert "require is not defined" not in out, (
        "_runPyProgram still throws ReferenceError; the four tools that call "
        "it are registered but cannot run")
    assert out.startswith("RAN"), out
