#!/usr/bin/env python3
"""generated_artifact_conflict_resolve.py — resolve the merge conflicts that
carry no information, and REFUSE every conflict that does.

THE DEFECT (vibe-ic#1363), measured
===================================
`programs/INDEX.md` is a DERIVED artefact — its own first line says
`AUTO-GENERATED by tools/gen_programs_index.py — DO NOT EDIT BY HAND`, a
freshness test regenerates it and FAILs on drift, and `tools/ci/
repo_hygiene_gates.sh` runs the generator's `--check` on every landing. It is
also COMMITTED, and git 3-way-merges it as ordinary text.

So every PR that adds a program rewrites the same generated lines, and any one
landing makes the alphabetically-adjacent ones conflict. Measured over all 163
open PRs at `24ff9530`: 29 conflicting, and **26 of them conflicted on
`programs/INDEX.md` and on nothing else**. Three PRs disagreed about real
content. The repo's conflict rate was one unmanaged generated file.

Because the resolution never depends on what either side wrote — regenerate,
stage, done — the conflict carries NO INFORMATION. A conflict that is always
resolved the same way is pure cost, and it is paid once per PR per landing.

WHY A PROGRAM AND NOT A MERGE DRIVER
====================================
The obvious answer is `.gitattributes` + a merge driver. Both variants were
measured on git 2.43.0 and both are dead ends:

  `merge=ours`, attribute alone   NO-OP. `ours` is not one of git's built-in
                                  drivers (`text`/`binary`/`union` are), so
                                  without a per-clone `merge.ours.driver` the
                                  merge still conflicts: rc=1, 2 markers.

  `merge=ours` + the config       Merges clean — AND STILL CANNOT LAND. The
                                  incoming side's row is silently dropped, so
                                  `gen_programs_index.py --check` goes rc=1
                                  (`INDEX.md is stale`). The refusal MOVES from
                                  the merge to the freshness gate; it does not
                                  go away. Nothing is unblocked.

  a driver that REGENERATES       IMPOSSIBLE. A merge driver runs BEFORE the
                                  working tree is complete. Instrumented on the
                                  two-adjacent-programs repro, at driver time:
                                      zz_probe_aaa.py on disk: YES
                                      zz_probe_aab.py on disk: NO
                                  and `YES` only after the merge returned. A
                                  driver that regenerates therefore emits an
                                  INDEX missing exactly the program the incoming
                                  side added — a wrong answer, confidently.

Regeneration is only correct AFTER the file-level merge finishes. That is what
this program does, and it is why it is a post-merge step rather than a merge
policy.

WHAT IT REFUSES, AND WHY THAT IS THE POINT
==========================================
The hand recipe posted on #1253 is `git merge; regenerate; git add`. It has no
guard: run it on a merge that conflicted on INDEX.md **and** on a real file and
it stages a regenerated catalog on top of an unresolved conflict, which looks
like progress. So the verdict here is not "regenerate" — it is:

    is every conflicted path a registered derived artefact?

and a single foreign path REFUSES THE WHOLE RESOLUTION, including the derived
half. Partially resolving hides a real conflict behind a smaller-looking one,
and a human is in the loop for the foreign path anyway.

EVERY WAY THIS CAN DEGRADE, DEGRADES TOWARD REFUSING
====================================================
  no conflict in progress          rc=2 — a resolver that reports a resolution
                                   it did not perform is a liar.
  regenerator absent (cache tree)  rc=2 — not "nothing to do".
  regenerator non-zero / times out rc=2 — an unmeasured tree is not a clean one.
  markers survive regeneration     rc=2 — the artefact is not fully derived.
  `--check` still red afterwards   rc=2 — the bytes written are not the bytes
                                   the freshness gate demands, so staging them
                                   would only move the failure again.
  a path still conflicted after    rc=2.
  a foreign conflicted path        rc=1, and it is NAMED.

Only "every conflicted path is registered, regenerated, verified fresh, and
staged" exits 0.

THE INNER TIMEOUT IS 60s AND THAT IS A CEILING, NOT AN ESTIMATE
===============================================================
The landing harness runs at `--timeout=180 --timeout-method=thread`. An inner
bound above that lets one hung regenerator kill the whole SESSION instead of one
step, losing every other result in the run unnamed. So the bound is 60s.

`gen_programs_index.py` over 1165 files measured 25-28s warm and EXCEEDED 60s on
a cold tree (first run after a `git worktree add`). A cold-tree timeout is
therefore expected and is reported as rc=2 with that fact in the message — the
question could not be put, which is not the same as an answer.

Usage:
    generated_artifact_conflict_resolve.py [--repo DIR] [--dry-run] [--json OUT]

Exit codes:
    0 = RESOLVED     every conflicted path was a registered derived artefact;
                     each was regenerated, verified fresh, and staged
    1 = REFUSED      at least one conflicted path is not a derived artefact
    2 = UNMEASURABLE the question could not be put (see the table above)
"""
from __future__ import annotations

import argparse
import collections
import importlib
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parent))  # so the sibling import below resolves however this is invoked
from _atomic_artefact import write_json  # noqa: E402  vibe-ic#1082 (helper from PR #1094)

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _progress_run as _pr  # noqa: E402

# The landing harness runs at --timeout=180 --timeout-method=thread; an inner
# bound above that turns one hung regenerator into a lost SESSION.
SUBPROCESS_TIMEOUT_S = 60

CONFLICT_MARKERS = ("<<<<<<< ", "=======", ">>>>>>> ")


# ─── the registry ───────────────────────────────────────────────────
@dataclass(frozen=True)
class DerivedArtifact:
    """A COMMITTED file whose correct bytes are a pure function of the tree.

    `regenerate` writes those bytes; `check` exits 0 iff the committed bytes
    already are those bytes. Both are argv run at the REPO ROOT. `generator`
    is the path that must exist for the entry to be usable at all — on the
    flattened plugin cache the repo-root tools are absent, and that is an
    UNMEASURABLE state, not a clean one.
    """

    path: str
    generator: str
    regenerate: tuple[str, ...]
    check: tuple[str, ...]


_INV = "vibe-ic-marketplace/plugins/vibe-ic/programs/gen_program_inventory.py"

REGISTRY: tuple[DerivedArtifact, ...] = (
    DerivedArtifact(
        path="vibe-ic-marketplace/plugins/vibe-ic/programs/INDEX.md",
        generator="tools/gen_programs_index.py",
        regenerate=("python3", "tools/gen_programs_index.py"),
        check=("python3", "tools/gen_programs_index.py", "--check"),
    ),
    # PROGRAM_INVENTORY.json is the SECOND file every program-adding branch
    # rewrites, and it conflicted alongside INDEX.md on a real merge of
    # jdistmat/matrix-distil into main a4caccefe. Unregistered, it was named as
    # a FOREIGN path and refused the whole resolution -- including the derived
    # half that was resolvable -- so the merge was finished by hand.
    #
    # `--check-artifact`, NOT `--check`, and `--artifact-only`, NOT a bare run.
    # BOTH flags exist because THIS entry's contract is ONE registered path:
    # `regenerate` writes it, `check` verifies it, and `_resolve` stages
    # exactly it.
    #
    # Full --check also binds the stated counts in the two READMEs. Registered
    # with --check, this entry would leave `check` red after a correct
    # regeneration, and the degradation table above turns that into rc 2,
    # UNMEASURABLE -- reporting an unmeasurable tree where the artefact is
    # provably correct. Measured when this comment was first written: with the
    # JSON freshly regenerated, --check was still red on five README lines.
    #
    # That was five because a bare run could not write prose AT ALL, which is
    # the round trip v1.13.3's follow-up closed: a bare run now rewrites the
    # counts that quote the artefact. Good everywhere else, wrong HERE -- a
    # resolver that corrected prose would leave a correct edit unstaged and
    # outside its own verdict, and this program's whole claim is that what it
    # regenerated is what it staged. So it asks for the artefact alone, by
    # name, rather than relying on a default that has now legitimately grown.
    DerivedArtifact(
        path="vibe-ic-marketplace/plugins/vibe-ic/programs/PROGRAM_INVENTORY.json",
        generator=_INV,
        regenerate=("python3", _INV, "--artifact-only"),
        check=("python3", _INV, "--check-artifact"),
    ),
)


# ─── the PARTIAL registry ───────────────────────────────────────────
#: `vibe-ic-marketplace/` is where `gen_program_inventory` names its documents
#: from; the whole-file REGISTRY above spells the same prefix out, and this
#: keeps the two halves of one file talking about paths the same way.
_MKT = "vibe-ic-marketplace/"


@dataclass(frozen=True)
class PartialArtifact:
    """A HAND-AUTHORED document a generator owns SOME LINES of.

    Unlike a `DerivedArtifact`, its correct bytes are not a pure function of the
    tree — only its counter lines are — so it can never be regenerated from
    scratch, and "is this conflict resolvable?" is not a question about the
    PATH. It is a question about the LINES the two sides disagree about.

    WHY THIS EXISTS (vibe-ic#2137 addendum, lane czrailmeas / #2077)
    ---------------------------------------------------------------
    The two READMEs carry the tree-wide counters `gen_program_inventory` writes,
    embedded in prose it does not. Two branches that add a different NUMBER of
    programs produce different counters, git conflicts on them, and — classified
    per PATH — both READMEs were named `CONFLICT (real)` and the WHOLE
    resolution refused, including the INDEX.md/PROGRAM_INVENTORY.json half that
    was resolvable. Reproduced on this tree (a 1-program branch merged with a
    2-program-plus-1-test branch): rc=1, both READMEs named, and every single
    conflicting line one of these counters.

    Fail-closed, so nothing wrong was ever committed — but every such rebase
    paid a hand-resolve, and the one tool written for this conflict class did
    not cover the two files its own docstring names first.
    """

    path: str
    generator: str
    regenerate: tuple[str, ...]
    check: tuple[str, ...]
    owned: tuple[re.Pattern, ...]


def _inventory_claim_patterns() -> dict[str, tuple[re.Pattern, ...]]:
    """{repo-relative document: the line forms `gen_program_inventory` WRITES}.

    DERIVED FROM THE WRITER — `gen_program_inventory._CLAIMS` is the list that
    program uses to find and rewrite each stated count, so it is the same
    authority that produced the conflicting lines in the first place. A regex
    typed HERE would be a second implementation of that rule, and the file this
    lives in already carries the lesson: "two implementations of one rule give
    two answers to that merge, and the weaker one was the one with a caller".
    A claim form added to the generator is inside this boundary automatically.

    `_NOT_A_POPULATION_COUNT` is deliberately NOT included. Those are numbers
    the generator explicitly does NOT own, so a disagreement on one is a real
    disagreement.

    Returns `{}` when the generator cannot be imported (the flattened plugin
    cache has no `programs/` sibling). That empties the partial registry, and
    an empty partial registry is exactly the behaviour that shipped before this
    existed: the paths are foreign and the whole resolution is refused. The
    degradation is fail-closed by construction, not by a branch that remembers.
    """
    try:
        gpi = importlib.import_module("gen_program_inventory")
        claims = gpi._CLAIMS
    except Exception:
        return {}
    out: dict[str, list[re.Pattern]] = {}
    for entry in claims:
        try:
            rel, _key, pattern = entry
            rx = re.compile(pattern)
        except (TypeError, ValueError, re.error):
            # One unusable entry must not silently shrink the authority: an
            # incomplete pattern set would call a real disagreement resolvable.
            return {}
        out.setdefault(_MKT + rel, []).append(rx)
    return {k: tuple(v) for k, v in out.items()}


def build_partial_registry() -> tuple[PartialArtifact, ...]:
    """The partial artefacts, or `()` when the writer could not be consulted."""
    patterns = _inventory_claim_patterns()
    return tuple(
        PartialArtifact(
            path=path,
            generator=_INV,
            # The prose-writing run, NOT `--artifact-only`: these lines ARE the
            # prose. The full `--check` for the same reason — here it is the
            # right question, where for PROGRAM_INVENTORY.json it was the wrong
            # one (see that entry).
            regenerate=("python3", _INV),
            check=("python3", _INV, "--check"),
            owned=owned,
        )
        for path, owned in sorted(patterns.items())
    )


PARTIAL_REGISTRY: tuple[PartialArtifact, ...] = build_partial_registry()


# ─── conflict hunks, and what a side actually disputes ──────────────
def parse_conflict_hunks(text: str):
    """`[(ours, theirs)]` per conflict region, or `None` if unparseable.

    `None` is not "no hunks". A file whose markers do not nest the way git
    writes them has not been read, and the caller must refuse rather than
    conclude that nothing is disputed — the forgiving direction here commits
    somebody else's edit.

    The `|||||||` base section of a diff3/zdiff3 conflict is discarded: it is
    the common ancestor, not a side, and neither side is being asked to keep it.
    """
    hunks = []
    ours = theirs = None
    where = None            # None | "ours" | "base" | "theirs"
    for line in text.splitlines():
        if line.startswith("<<<<<<< "):
            if where is not None:
                return None
            ours, theirs, where = [], [], "ours"
        elif line.startswith("|||||||") and where == "ours":
            where = "base"
        elif line.startswith("=======") and where in ("ours", "base"):
            where = "theirs"
        elif line.startswith(">>>>>>> "):
            if where != "theirs":
                return None
            hunks.append((ours, theirs))
            ours = theirs = where = None
        elif where == "ours":
            ours.append(line)
        elif where == "theirs":
            theirs.append(line)
        elif where == "base":
            pass
    return None if where is not None else hunks


def disputed_lines(ours, theirs) -> list[str]:
    """The lines the two sides actually disagree about.

    A MULTISET difference both ways, so a line present on both sides drops out
    wherever it sits in the hunk — which is the whole point: git puts prose
    IDENTICAL on both sides inside a conflict region whenever it lies between
    two lines that differ, and per-path classification then reads that prose as
    disagreement. Counting rather than set-differencing means a line duplicated
    on one side only is still disputed.
    """
    a, b = collections.Counter(ours), collections.Counter(theirs)
    out = []
    for line, n in (a - b).items():
        out.extend([line] * n)
    for line, n in (b - a).items():
        out.extend([line] * n)
    return out


def owned_lines(document: str, owned) -> set:
    """The LINES of `document` a claim pattern covers, by content.

    MATCHED THE WAY THE WRITER MATCHES, then mapped down to lines — not applied
    line by line. Two of `gen_program_inventory`'s own claim forms span a
    newline (`It is \\*\\*(N) top-level Python\\nprograms\\*\\*` and
    `the other\\n(N) are helper modules and shims`), so a per-line regex sees
    neither, calls both halves unowned, and refuses a conflict that is nothing
    but counters. Measured: with per-line matching the reproduction below still
    refused `plugins/vibe-ic/README.md` on exactly those two forms.

    The document handed in is the WHOLE side, every hunk already resolved to it,
    so a claim that starts inside a hunk and ends outside it is still found. A
    line no pattern covers is simply not in the set, and the caller refuses —
    the truncating direction here is the safe one.
    """
    lines = document.splitlines()
    covered = set()
    for rx in owned:
        for m in rx.finditer(document):
            first = document.count("\n", 0, m.start())
            last = document.count("\n", 0, m.end())
            covered.update(range(first, last + 1))
    return {lines[i] for i in covered if 0 <= i < len(lines)}


def conflict_is_generated_only(text: str, owned) -> Optional[bool]:
    """Is every line the two sides disagree about one the generator writes?

    `None` when the markers do not parse — not `False`, because the caller must
    be able to tell "this conflict is a real disagreement" from "this conflict
    was never read". Both refuse; only one of them is a fact about the file.
    """
    hunks = parse_conflict_hunks(text)
    if hunks is None:
        return None
    ours_doc, theirs_doc = take_ours(text), take_theirs(text)
    if ours_doc is None or theirs_doc is None:
        return None
    ours_owned = owned_lines(ours_doc, owned)
    theirs_owned = owned_lines(theirs_doc, owned)
    for ours, theirs in hunks:
        for line in disputed_lines(ours, theirs):
            if line not in ours_owned and line not in theirs_owned:
                return False
    return True


def _take_side(text: str, keep: str) -> Optional[str]:
    """`text` with every conflict region replaced by one side, or `None`.

    For the WRITE this is only ever called with `keep="ours"`, and only on a
    file already proved generated-only, where the two sides differ ONLY on
    lines the generator is about to overwrite — so which side is taken cannot
    decide anything, and the regeneration that follows, not this choice, is
    what puts the right numbers in. Taking a side there is marker removal, not
    conflict resolution. Both sides are also built for READING, to match the
    generator's claim patterns against a whole document.
    """
    out, where = [], None
    for line in text.splitlines(keepends=True):
        bare = line.rstrip("\n")
        if bare.startswith("<<<<<<< "):
            if where is not None:
                return None
            where = "ours"
        elif bare.startswith("|||||||") and where == "ours":
            where = "base"
        elif bare.startswith("=======") and where in ("ours", "base"):
            where = "theirs"
        elif bare.startswith(">>>>>>> "):
            if where != "theirs":
                return None
            where = None
        elif where is None or where == keep:
            out.append(line)
    return None if where is not None else "".join(out)


def take_ours(text: str) -> Optional[str]:
    return _take_side(text, "ours")


def take_theirs(text: str) -> Optional[str]:
    return _take_side(text, "theirs")


# ─── the verdict ────────────────────────────────────────────────────
@dataclass
class Verdict:
    code: int                       # 0 RESOLVED / 1 REFUSED / 2 UNMEASURABLE
    reason: str
    conflicted: tuple[str, ...] = ()
    derived: tuple[str, ...] = ()   # conflicted AND registered (whole-file)
    partial: tuple[str, ...] = ()   # conflicted AND every disputed line is generated
    foreign: tuple[str, ...] = ()   # conflicted AND carrying a real disagreement
    regenerated: list[str] = field(default_factory=list)
    staged: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "code": self.code,
            "verdict": {0: "RESOLVED", 1: "REFUSED", 2: "UNMEASURABLE"}[self.code],
            "reason": self.reason,
            "conflicted": list(self.conflicted),
            "derived": list(self.derived),
            "partial": list(self.partial),
            "foreign": list(self.foreign),
            "regenerated": list(self.regenerated),
            "staged": list(self.staged),
        }


def decide(
    conflicted: Sequence[str],
    registry: Sequence[DerivedArtifact] = REGISTRY,
    partial_registry: Sequence[PartialArtifact] = (),
    conflict_text: Optional[dict] = None,
) -> Verdict:
    """THE DECISION, in one function, with no side effects.

    Kept separate from the regeneration so a mutant that neuters the refusal
    has exactly one site to neuter and has to leave every other line standing —
    which is the only way to show the tests read the DECISION and not the
    plumbing.

    PER PATH, THEN PER LINE (#2137 addendum). A whole-file derived artefact is
    resolvable because of WHAT IT IS. A partial artefact is resolvable only
    because of WHAT THIS CONFLICT SAYS, so it needs the conflict: pass its
    parsed hunks in `hunks_by_path` (`{path: [(ours, theirs)] | None}`).

    THE DEFAULT IS THE OLD BEHAVIOUR, deliberately. With no partial registry
    and no hunks — the signature every existing caller and test uses — a
    partial path is foreign and the whole resolution is refused, exactly as
    before. Every widening here has to be asked for, and a path whose conflict
    could not be read (`None`) is refused rather than assumed benign: "I could
    not read the conflict" is not "the conflict is only counters".
    """
    conflicted = tuple(sorted(set(conflicted)))
    known = {a.path for a in registry}
    partial_by_path = {a.path: a for a in partial_registry}
    if not conflicted:
        return Verdict(
            2,
            "no conflicted path — this resolver was invoked outside a "
            "conflicted merge, and a resolver that reports a resolution it did "
            "not perform is worse than one that refuses",
        )
    derived = tuple(p for p in conflicted if p in known)

    partial: list[str] = []
    foreign: list[str] = []
    for rel in conflicted:
        if rel in known:
            continue
        art = partial_by_path.get(rel)
        text = (conflict_text or {}).get(rel)
        if art is None or text is None:
            foreign.append(rel)
            continue
        if conflict_is_generated_only(text, art.owned) is True:
            partial.append(rel)
        else:
            foreign.append(rel)

    if foreign:
        return Verdict(
            1,
            f"{len(foreign)} conflicted path(s) carry real disagreement and "
            f"cannot be regenerated; refusing the whole resolution so the "
            f"derived half cannot hide them",
            conflicted=conflicted,
            derived=derived,
            partial=tuple(partial),
            foreign=tuple(foreign),
        )
    if partial:
        return Verdict(
            0,
            f"every conflicted path is regenerable: {len(derived)} derived "
            f"artefact(s), and {len(partial)} document(s) whose every disputed "
            f"line is a counter the generator writes",
            conflicted=conflicted,
            derived=derived,
            partial=tuple(partial),
        )
    return Verdict(
        0,
        f"every conflicted path ({len(derived)}) is a registered derived "
        f"artefact",
        conflicted=conflicted,
        derived=derived,
    )


# ─── the git surface ────────────────────────────────────────────────
def _git(root: Path, *args: str) -> subprocess.CompletedProcess:
    return _pr.run(
        ("git", "-C", str(root)) + args,
        capture_output=True,
        text=True,
        
    )


def conflicted_paths(root: Path) -> Optional[tuple[str, ...]]:
    """Repo-relative paths git reports as unmerged, or None if it could not
    be asked (which is UNMEASURABLE, never an empty list)."""
    try:
        cp = _git(root, "diff", "--name-only", "--diff-filter=U")
    except (OSError, subprocess.SubprocessError):
        return None
    if cp.returncode != 0:
        return None
    return tuple(p for p in cp.stdout.splitlines() if p.strip())


def _has_markers(p: Path) -> bool:
    try:
        text = p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return True  # unreadable is not "clean"
    return any(
        line.startswith(m) for line in text.splitlines() for m in CONFLICT_MARKERS
    )


def _conflict_text_for(root: Path, paths: Sequence[str],
                       partial_registry: Sequence[PartialArtifact]) -> dict:
    """`{path: raw text | None}` for each conflicted PARTIAL path.

    `None` for a file that could not be read; `decide` refuses on `None`, so an
    unreadable conflict never reaches the resolvable side.
    """
    known = {a.path for a in partial_registry}
    out = {}
    for rel in paths:
        if rel not in known:
            continue
        try:
            out[rel] = (root / rel).read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            out[rel] = None
    return out


def resolve(
    root: Path,
    registry: Sequence[DerivedArtifact] = REGISTRY,
    dry_run: bool = False,
    partial_registry: Sequence[PartialArtifact] = PARTIAL_REGISTRY,
) -> Verdict:
    """Read the conflicted set, decide, and — only on a RESOLVED decision and
    only when not a dry run — regenerate, verify, and stage."""
    paths = conflicted_paths(root)
    if paths is None:
        return Verdict(2, f"git could not report the unmerged paths under {root}")
    v = decide(paths, registry, partial_registry,
               _conflict_text_for(root, paths, partial_registry))
    if v.code != 0 or dry_run:
        if dry_run and v.code == 0:
            v.reason += " (dry run — nothing was regenerated or staged)"
        return v

    by_path = {a.path: a for a in registry}
    for rel in v.derived:
        art = by_path[rel]
        gen = root / art.generator
        if not gen.exists():
            return Verdict(
                2,
                f"{rel}: its generator {art.generator} is not present under "
                f"{root} (the repo-root tools are absent on the flattened "
                f"plugin cache); the artefact cannot be regenerated here",
                conflicted=v.conflicted, derived=v.derived,
            )
        try:
            cp = _pr.run(
                art.regenerate, cwd=str(root), capture_output=True,
                text=True)
        except _pr.Stalled:
            return Verdict(
                2,
                f"{rel}: {' '.join(art.regenerate)} STOPPED MAKING PROGRESS "
                f"and was killed. A cold tree is no longer the explanation — "
                f"this generator measured 25-28s warm and over 60s cold, and "
                f"both now run to completion. The question was not answered.",
                conflicted=v.conflicted, derived=v.derived,
            )
        except OSError as e:
            return Verdict(
                2, f"{rel}: {' '.join(art.regenerate)} could not be run: {e}",
                conflicted=v.conflicted, derived=v.derived,
            )
        if cp.returncode != 0:
            return Verdict(
                2,
                f"{rel}: {' '.join(art.regenerate)} exited {cp.returncode}; "
                f"an unmeasured tree is not a clean one. "
                f"{(cp.stderr or cp.stdout).strip()[:300]}",
                conflicted=v.conflicted, derived=v.derived,
            )
        v.regenerated.append(rel)

        if _has_markers(root / rel):
            return Verdict(
                2,
                f"{rel}: conflict markers SURVIVED regeneration, so this file "
                f"is not fully derived from the tree and the registry entry is "
                f"wrong about it",
                conflicted=v.conflicted, derived=v.derived,
                regenerated=v.regenerated,
            )

        try:
            chk = subprocess.run(
                art.check, cwd=str(root), capture_output=True,
                text=True, timeout=SUBPROCESS_TIMEOUT_S,
            )
        except (OSError, subprocess.SubprocessError) as e:
            return Verdict(
                2, f"{rel}: {' '.join(art.check)} could not be run: {e}",
                conflicted=v.conflicted, derived=v.derived,
                regenerated=v.regenerated,
            )
        if chk.returncode != 0:
            return Verdict(
                2,
                f"{rel}: regenerated, but {' '.join(art.check)} is still "
                f"rc={chk.returncode} — the bytes written are not the bytes the "
                f"freshness gate demands, so staging them would only move the "
                f"failure. {(chk.stderr or chk.stdout).strip()[:300]}",
                conflicted=v.conflicted, derived=v.derived,
                regenerated=v.regenerated,
            )

        add = _git(root, "add", "--", rel)
        if add.returncode != 0:
            return Verdict(
                2, f"{rel}: git add failed: {add.stderr.strip()[:300]}",
                conflicted=v.conflicted, derived=v.derived,
                regenerated=v.regenerated, staged=v.staged,
            )
        v.staged.append(rel)

    # ── the PARTIAL pass (#2137 addendum) ───────────────────────────
    # Runs AFTER the whole-file artefacts, because the generator invoked here
    # writes PROGRAM_INVENTORY.json too and the derived pass has just verified
    # and staged it: a second write of identical bytes is a no-op, and a write
    # of different bytes is a fact this pass must not leave unstaged.
    if v.partial:
        by_partial = {a.path: a for a in partial_registry}
        art = by_partial[v.partial[0]]
        # Same generator for every partial path by construction (they are the
        # documents of ONE writer), asserted rather than assumed.
        others = [by_partial[r].generator for r in v.partial[1:]]
        if any(g != art.generator for g in others):
            return Verdict(
                2,
                "the partial artefacts name more than one generator; this pass "
                "runs the writer ONCE and cannot say which run owns which line",
                conflicted=v.conflicted, derived=v.derived, partial=v.partial,
                regenerated=v.regenerated, staged=v.staged,
            )
        if not (root / art.generator).exists():
            return Verdict(
                2,
                f"the counter documents' generator {art.generator} is not "
                f"present under {root}; their conflicts cannot be regenerated "
                f"here",
                conflicted=v.conflicted, derived=v.derived, partial=v.partial,
                regenerated=v.regenerated, staged=v.staged,
            )

        # WHAT WAS ALREADY DIRTY, recorded BEFORE anything is written. The
        # boundary below asks "what did THIS RUN write", and a worktree diff
        # taken only afterwards cannot answer that: it also names every file
        # the operator had modified before invoking the resolver, and refusing
        # a resolvable conflict because of an unrelated edit is a false
        # refusal. Measured while proving this pass: the copy of THIS FILE
        # under test was dirty in the reproduction tree and was reported as a
        # path the generator wrote.
        pre = _git(root, "diff", "--name-only")
        if pre.returncode != 0:
            return Verdict(
                2, f"git could not report the worktree changes before "
                   f"regeneration: {pre.stderr.strip()[:200]}",
                conflicted=v.conflicted, derived=v.derived, partial=v.partial,
                regenerated=v.regenerated, staged=v.staged,
            )
        already_dirty = {q for q in pre.stdout.splitlines() if q.strip()}

        # Marker removal FIRST — the generator rewrites counts in place and
        # would otherwise be asked to parse a file with `<<<<<<<` in it.
        for rel in v.partial:
            src = root / rel
            try:
                cleaned = take_ours(src.read_text(encoding="utf-8"))
            except (OSError, UnicodeDecodeError) as e:
                return Verdict(
                    2, f"{rel}: could not be read to remove its markers: {e}",
                    conflicted=v.conflicted, derived=v.derived,
                    partial=v.partial, regenerated=v.regenerated,
                    staged=v.staged,
                )
            if cleaned is None:
                return Verdict(
                    2,
                    f"{rel}: its conflict markers did not parse on the second "
                    f"reading, though they did on the first; the file changed "
                    f"underneath this resolution",
                    conflicted=v.conflicted, derived=v.derived,
                    partial=v.partial, regenerated=v.regenerated,
                    staged=v.staged,
                )
            src.write_text(cleaned)

        try:
            cp = _pr.run(art.regenerate, cwd=str(root), capture_output=True,
                         text=True)
        except _pr.Stalled:
            return Verdict(
                2,
                f"{' '.join(art.regenerate)} STOPPED MAKING PROGRESS and was "
                f"killed; the counter documents were not regenerated",
                conflicted=v.conflicted, derived=v.derived, partial=v.partial,
                regenerated=v.regenerated, staged=v.staged,
            )
        except OSError as e:
            return Verdict(
                2, f"{' '.join(art.regenerate)} could not be run: {e}",
                conflicted=v.conflicted, derived=v.derived, partial=v.partial,
                regenerated=v.regenerated, staged=v.staged,
            )
        if cp.returncode != 0:
            return Verdict(
                2,
                f"{' '.join(art.regenerate)} exited {cp.returncode}; an "
                f"unmeasured tree is not a clean one. "
                f"{(cp.stderr or cp.stdout).strip()[:300]}",
                conflicted=v.conflicted, derived=v.derived, partial=v.partial,
                regenerated=v.regenerated, staged=v.staged,
            )
        v.regenerated.extend(v.partial)

        for rel in v.partial:
            if _has_markers(root / rel):
                return Verdict(
                    2,
                    f"{rel}: conflict markers SURVIVED both the marker removal "
                    f"and the regeneration",
                    conflicted=v.conflicted, derived=v.derived,
                    partial=v.partial, regenerated=v.regenerated,
                    staged=v.staged,
                )

        # THE BOUNDARY (#1029). The writer may legitimately have corrected a
        # counter in a document that was NOT conflicted — the correct count is
        # a function of the MERGED tree, which neither side had. Every such
        # path must be a DECLARED surface of this resolver and must be staged,
        # because a correct edit left unstaged and outside the verdict is the
        # failure mode this program exists to avoid. Anything else it touched
        # is a refusal, printed with the path.
        declared = {a.path for a in registry} | {a.path for a in partial_registry}
        dirty = _git(root, "diff", "--name-only")
        if dirty.returncode != 0:
            return Verdict(
                2, f"git could not report the worktree changes after "
                   f"regeneration: {dirty.stderr.strip()[:200]}",
                conflicted=v.conflicted, derived=v.derived, partial=v.partial,
                regenerated=v.regenerated, staged=v.staged,
            )
        touched = [q for q in dirty.stdout.splitlines() if q.strip()
                   and (q not in already_dirty or q in v.partial)]
        outside = sorted(q for q in touched if q not in declared)
        if outside:
            return Verdict(
                2,
                f"{' '.join(art.regenerate)} wrote {len(outside)} path(s) "
                f"outside this resolver's declared surfaces "
                f"({', '.join(outside[:5])}); nothing further was staged",
                conflicted=v.conflicted, derived=v.derived, partial=v.partial,
                regenerated=v.regenerated, staged=v.staged,
            )

        try:
            chk = subprocess.run(art.check, cwd=str(root), capture_output=True,
                                 text=True, timeout=SUBPROCESS_TIMEOUT_S)
        except (OSError, subprocess.SubprocessError) as e:
            return Verdict(
                2, f"{' '.join(art.check)} could not be run: {e}",
                conflicted=v.conflicted, derived=v.derived, partial=v.partial,
                regenerated=v.regenerated, staged=v.staged,
            )
        if chk.returncode != 0:
            return Verdict(
                2,
                f"the counter documents were regenerated, but "
                f"{' '.join(art.check)} is still rc={chk.returncode} — the "
                f"bytes written are not the bytes the freshness gate demands. "
                f"{(chk.stderr or chk.stdout).strip()[:300]}",
                conflicted=v.conflicted, derived=v.derived, partial=v.partial,
                regenerated=v.regenerated, staged=v.staged,
            )

        for rel in sorted(set(v.partial) | set(touched)):
            add = _git(root, "add", "--", rel)
            if add.returncode != 0:
                return Verdict(
                    2, f"{rel}: git add failed: {add.stderr.strip()[:300]}",
                    conflicted=v.conflicted, derived=v.derived,
                    partial=v.partial, regenerated=v.regenerated,
                    staged=v.staged,
                )
            if rel not in v.staged:
                v.staged.append(rel)

    left = conflicted_paths(root)
    if left is None:
        return Verdict(
            2, "git could not re-report the unmerged paths after staging",
            conflicted=v.conflicted, derived=v.derived,
            regenerated=v.regenerated, staged=v.staged,
        )
    if left:
        return Verdict(
            2,
            f"{len(left)} path(s) are STILL unmerged after staging "
            f"({', '.join(left)}); the resolution did not take",
            conflicted=v.conflicted, derived=v.derived,
            regenerated=v.regenerated, staged=v.staged,
        )
    return v


# ─── CLI ────────────────────────────────────────────────────────────
def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        description="Resolve merge conflicts on registered derived artefacts; "
                    "refuse every other conflict."
    )
    ap.add_argument("--repo", default=".",
                    help="repo root (default: cwd)")
    ap.add_argument("--dry-run", action="store_true",
                    help="report the verdict without regenerating or staging")
    ap.add_argument("--json", dest="json_out", default=None,
                    help="write the verdict record to this path")
    a = ap.parse_args(argv)

    root = Path(a.repo).resolve()
    top = None
    try:
        cp = _git(root, "rev-parse", "--show-toplevel")
        if cp.returncode == 0 and cp.stdout.strip():
            top = Path(cp.stdout.strip())
    except (OSError, subprocess.SubprocessError):
        top = None
    if top is None:
        v = Verdict(2, f"{root} is not inside a git work tree")
    else:
        v = resolve(top, REGISTRY, dry_run=a.dry_run)

    if a.json_out:
        try:
            # vibe-ic#1082 / #1462: the verdict record is the artefact a later
            # reader opens to learn whether the merge was resolved or refused.
            # `.write_text` creates that name before filling it, so a death
            # mid-write leaves a truncated record under the name a
            # `required_outputs` check reads as "this step produced its
            # evidence". `ensure_ascii=True` keeps the payload byte-identical
            # to the call this replaces — the conversion moves WHEN the name
            # appears, never WHAT is written.
            write_json(a.json_out, v.to_dict(), ensure_ascii=True)
        except OSError as e:
            print(f"[WARN] could not write {a.json_out}: {e}", file=sys.stderr)

    if v.code == 1:
        for p in v.foreign:
            print(f"  CONFLICT (real)  {p}", file=sys.stderr)
        print(f"[REFUSED] {v.reason}", file=sys.stderr)
    elif v.code == 2:
        print(f"[UNMEASURABLE] {v.reason}", file=sys.stderr)
    else:
        for p in v.partial:
            print(f"  counters only         {p}", file=sys.stderr)
        for p in v.staged:
            print(f"  regenerated + staged  {p}", file=sys.stderr)
        print(f"[RESOLVED] {v.reason}.", file=sys.stderr)
    return v.code


if __name__ == "__main__":
    # A stall is not a verdict about the commit: reach the stamp as rc 2
    # (this gate's 'could not measure'), announced, never as a finding.
    raise SystemExit(_pr.exit_undetermined_on_stall(main))
