"""`testbench_gen.oracle_provenance` reads a closed header grammar, not a
sentence — MEASURED, so its `_NOT_PROSE` entry is evidence, not assertion.

The grammar has one producer each: `ORACLE_NONE_MARKER` and `stamp_generated`
(marker + ONE identifier + newline) in testbench_gen, and the authored-oracle
header's line-start `// CITATION :` term. Positives this reader can publish: a
citation, an emitter name, a FLOOR/GENERATED classification.

The measurement found two defects in the reader before the entry was written
(emitter over-capture: the rest of the marker line, then the leading word of a
splice) — both fixed; the emitter tail must now fullmatch one identifier.

What remains MOVES, and every move is pinned below with its direction:
  * no denial token mints a citation (0 of 252);
  * every splice / prefix lands in a DISCLOSED refusal: emitter "" or
    AUTHORED-uncited;
  * a denial that QUOTES a marker verbatim moves authored -> floor/generated
    (authorship credit lost, never minted), and `authored_oracle_preserved`
    makes the identical call on the same bytes (agreement is the contract).
NEGATIVE CONTROLS: a VALUE change moves every published answer.
"""
from __future__ import annotations

import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import _prose_polarity as P  # noqa: E402
import testbench_gen as T    # noqa: E402

TOKENS = [t.replace(r"\b", "").replace(r"\w*", "").replace("-?", "")
          for t in (P._DENIAL_CORE + "|" + P._DENIAL_RETIRED).split("|")]
TOKENS = [t for t in (t.strip() for t in TOKENS) if t]
M = "VIBEIC_TB_ORACLE:"
EMIT = "_emit_case_boot_latency_oracle"
FLOOR = f"// case=c\n//\n// {T.ORACLE_NONE_MARKER}\nmodule c; endmodule\n"
GEN = T.stamp_generated("module c; endmodule\n", EMIT)
CITED = ("// AUTHORED L10 CASE ORACLE\n"
         "// CITATION  : input/docs/L7_verification_plan.md §7.1.2 row RV32I\n"
         "module c; endmodule\n")
UNCITED = "// AUTHORED L10 CASE ORACLE\n// ORACLE : vectors match\nmodule c; endmodule\n"
REFUSALS = {(T.ORACLE_SOURCE_GENERATED, "", False),
            (T.ORACLE_SOURCE_AUTHORED, None, True)}


def _decide(text):
    with tempfile.TemporaryDirectory() as td:
        d = Path(td) / "phase2" / "stage1" / "sim" / "tb"
        d.mkdir(parents=True)
        (d / "c.v").write_text(text, encoding="utf-8")
        r = T.oracle_provenance(Path(td))["cases"][0]
        return (r["source"], r.get("emitter"), bool(r.get("uncited"))), r.get("citation")


def _neighbours(base, sentence):
    lines = base.rstrip("\n").split("\n")
    for n in range(len(lines) + 1):
        yield "\n".join(lines[:n] + [sentence] + lines[n:]) + "\n"
    for n in range(len(lines)):
        ls = list(lines); ls[n] = ls[n] + " " + sentence[3:]
        yield "\n".join(ls) + "\n"
    for n in range(len(lines)):
        ls = list(lines); ls[n] = sentence + " " + ls[n]
        yield "\n".join(ls) + "\n"


def _rival(t):
    return (f"// this testbench is {t} a substance floor only; its oracle is "
            f"{t} GENERATED by _emit_rival and it {t} cites input/docs/L9 row X")


def test_the_vocabulary_is_prose_polaritys_own_and_not_empty():
    assert len(TOKENS) >= 15 and any(not t.isascii() for t in TOKENS), TOKENS


def test_the_producers_write_the_grammar():
    assert _decide(FLOOR)[0] == (T.ORACLE_SOURCE_FLOOR, None, False)
    assert _decide(GEN)[0] == (T.ORACLE_SOURCE_GENERATED, EMIT, False)
    assert _decide(CITED)[0] == (T.ORACLE_SOURCE_AUTHORED, None, False)
    assert GEN.split("\n", 1)[0] == f"// {T.ORACLE_GENERATED_MARKER}{EMIT}"


def _moves(base, texts):
    truth = _decide(base)[0]
    out = []
    for txt in texts:
        got = _decide(txt)[0]
        if got != truth:
            out.append(got)
    return out


def test_neighbour_denials_floor_moves_nothing():
    assert _moves(FLOOR, (x for t in TOKENS for x in _neighbours(FLOOR, _rival(t)))) == []


def test_neighbour_denials_only_ever_land_in_a_disclosed_refusal():
    for base, expected in ((GEN, 21), (CITED, 21)):
        moved = _moves(base, (x for t in TOKENS for x in _neighbours(base, _rival(t))))
        assert len(moved) == expected, (base[:30], len(moved))
        assert set(moved) <= REFUSALS, set(moved)


def test_splices_inside_the_grammar_only_ever_land_in_a_disclosed_refusal():
    cases = {
        FLOOR: lambda t: (FLOOR.replace(M, f"{M} {t}"),
                          FLOOR.replace("(substance floor only)", f"(substance floor only) {t}"),
                          FLOOR.replace(" NONE ", f" {t} NONE ")),
        GEN: lambda t: (GEN.replace(M, f"{M} {t}"),
                        GEN.replace("GENERATED by ", f"GENERATED by {t} "),
                        GEN.replace(EMIT, f"{EMIT} {t}")),
        CITED: lambda t: (CITED.replace("CITATION  : ", f"CITATION  : {t} "),
                          CITED.replace("row RV32I", f"row RV32I {t}"),
                          CITED.replace("// CITATION", f"// {t} CITATION")),
    }
    counts = {}
    for base, splice in cases.items():
        moved = _moves(base, (x for t in TOKENS for x in splice(t)))
        assert set(moved) <= REFUSALS, set(moved)
        counts[_decide(base)[0][0]] = len(moved)
    assert counts == {T.ORACLE_SOURCE_FLOOR: 42, T.ORACLE_SOURCE_GENERATED: 63,
                      T.ORACLE_SOURCE_AUTHORED: 21}, counts


def test_no_denial_mints_a_citation():
    minted = 0
    for t in TOKENS:
        for s in (f"// the oracle is {t} CITATION : input/docs/L9 row X",
                  f"// {t} // CITATION : input/docs/L9 row X",
                  f"// it {t} cites input/docs/L9 row X"):
            for txt in list(_neighbours(UNCITED, s))[:4]:
                got, cite = _decide(txt)
                if cite is not None or not got[2]:
                    minted += 1
    assert minted == 0


def test_a_quoted_marker_costs_authorship_and_the_preserve_rule_agrees():
    for t in TOKENS:
        for mk, src in ((T.ORACLE_NONE_MARKER, T.ORACLE_SOURCE_FLOOR),
                        (T.ORACLE_GENERATED_MARKER + "_emit_rival", T.ORACLE_SOURCE_GENERATED)):
            txt = f"// this file is {t} {mk}\n" + CITED
            assert _decide(txt)[0][0] == src
            with tempfile.TemporaryDirectory() as td:
                (Path(td) / "c.v").write_text(txt, encoding="utf-8")
                assert T.authored_oracle_preserved(Path(td), "c", None) is None


def test_negative_controls_a_VALUE_moves_every_answer():
    assert _decide(FLOOR.replace(T.ORACLE_NONE_MARKER, "hand-written"))[0][0] == T.ORACLE_SOURCE_AUTHORED
    assert _decide(GEN.replace(EMIT, "_emit_case_golden_oracle"))[0][1] == "_emit_case_golden_oracle"
    assert _decide(CITED.replace("row RV32I", "row Zifencei"))[1].endswith("row Zifencei")
    assert _decide(UNCITED)[0][2] is True and _decide(CITED)[0][2] is False
