"""Retired #146 materializer: machine deferrals cannot issue owner waivers."""
from __future__ import annotations

import json
import sys
from pathlib import Path

PLUGIN = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PLUGIN))
import waivers_materialize as WM  # noqa: E402
import flow_compliance_check as fcc  # noqa: E402
import waivers_schema_check as WS  # noqa: E402


def _mk_fpga_skip(tmp: Path) -> Path:
    d = tmp / "proj"
    (d / "reports" / "phase2" / "fpga").mkdir(parents=True)
    (d / "reports" / "phase2" / "fpga" / "quartus_map_audit.json").write_text(
        json.dumps({"verdict": "SKIP", "sof_present": False}))
    return d


def test_disclosed_fpga_skip_never_materializes_a_waiver(tmp_path):
    p = _mk_fpga_skip(tmp_path)
    n, ids = WM.materialize(p)
    assert (n, ids) == (0, [])
    assert not (p / "waivers.json").exists()


def test_no_materialized_file_is_substituted_for_owner_signature(tmp_path):
    p = _mk_fpga_skip(tmp_path)
    WM.materialize(p)
    assert not (p / "waivers.json").exists()
    findings, _ = WS.validate(p)
    assert [f for f in findings if f.severity == "error"] == []


def test_materialization_preserves_inmemory_coverage(tmp_path):
    # Neither the old in-memory path nor the file path may create approvals.
    p = _mk_fpga_skip(tmp_path)
    in_memory = WM.sanctioned_auto_waivers(p)
    WM.materialize(p)
    from_file = fcc._load_waivers(p)
    assert in_memory == from_file == {}


# ── §4.05 no-leak ──────────────────────────────────────────────────────────
def test_no_sanctioned_tier_writes_nothing(tmp_path):
    d = tmp_path / "proj"
    (d / "reports").mkdir(parents=True)
    n, _ = WM.materialize(d)
    assert n == 0 and not (d / "waivers.json").exists()   # honest MISSING


def test_never_clobbers_human_waivers(tmp_path):
    p = _mk_fpga_skip(tmp_path)
    human = {"waived_steps": [{
        "id": 6, "reason": "human decided to defer this board step deliberately",
        "approver": "alice", "review_required": True, "ticket": "JIRA-1"}]}
    (p / "waivers.json").write_text(json.dumps(human))
    n, _ = WM.materialize(p)
    assert n == 0
    assert json.loads((p / "waivers.json").read_text()) == human   # untouched


def test_self_approver_rejected_by_schema(tmp_path):
    # Historical records are read, refused, and never generated by the test path.
    p = _mk_fpga_skip(tmp_path)
    data = {"waived_steps": [{"id": 6,
             "reason": "A machine attempted to approve the missing board test",
             "approver": "agent", "review_required": True}]}
    (p / "waivers.json").write_text(json.dumps(data))
    findings, _ = WS.validate(p)
    assert any(f.severity == "error" for f in findings)


def test_existing_machine_file_is_preserved_as_refused_evidence(tmp_path):
    p = _mk_fpga_skip(tmp_path)
    data = {"_generator": "waivers_materialize.py", "waived_steps": [{
        "id": 6, "reason": "Legacy machine board waiver kept for audit history",
        "approver": "field-agent-attest (fpga-board cap-gap tier)",
        "auto_synthesized": True, "review_required": True}]}
    path = p / "waivers.json"
    path.write_text(json.dumps(data))
    before = path.read_bytes()
    assert WM.materialize(p) == (0, [])
    assert path.read_bytes() == before
    assert fcc._load_waivers(p) == {}
