"""Step 13 names the netlist step 15 routes for the module phase 3 BUILDS,
not for the runner's placeholder top.

MEASURED on the spm DIE run (source c06b4e718, image sha256:70ebc4fb..., run
2026-09-28; read-only copy at 192.168.1.108:/mnt/ssd2/mainred/spmic4/evidence):

* phase 2 was dispatched with ``--top-name chip_top``. The front door resolves
  the top BEFORE phase 2 (`vibe_ic_one_shot_runner._resolve_top_name`), and on
  this from-documents run the RTL does not exist yet at that point -- phase 2's
  own ``rtl_gen`` writes ``spm.v`` -- so the placeholder survives into phase 2.
  Phase 3 re-resolves after phase 2 and builds ``spm``.
* phase 2's Step-13 row: ``NOT_MEASURED`` -- "the netlist step 15 routes is not
  on disk yet (phase2/stage2/synth/chip_top_synth.v ...)" and
  ``reports/lec_not_run.json`` naming the same file.
* NO producer declares ``chip_top_synth.v``. The name is ``<top>_synth.v`` with
  the placeholder spliced in. Step 15 routed ``spm_synth.v`` (bridge receipt
  ``phase3/librelane/15-config/bridge/bridge_receipt.json`` nl[0], sha256
  d0cf12fc...) plus the phase-3-generated pad wrapper ``chip_top_io.v``; a
  ``chip_top`` netlist is never synthesised by anyone, so that row could never
  be measured and read to triage as "a phase-2 producer failed to emit
  chip_top_synth.v".

The defect is one resolution skipped: phase 3 main hands ``step_pnr``
``_chip_synth_read.effective_top(project, top_name)`` -- the ONE resolution
every phase-3 step shares -- while step 13's resolver asked
``pnr_input_netlist`` with the raw requested name. ``pnr_consumed_netlist`` now
applies the same resolution, and step 13's producer invocation (lec_run
``--top``) names the same module, so the proof, its receipt digest and the
router agree on one file.

Only lec_run's process is faked (it runs yosys in a container); the fake writes
the report lec_run writes, bound to the file and top it was handed.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

_PROGRAMS = Path(__file__).resolve().parent.parent
if str(_PROGRAMS) not in sys.path:
    sys.path.insert(0, str(_PROGRAMS))

import _chip_synth_read as CSR              # noqa: E402
import design_one_shot_runner as R          # noqa: E402
import lec_equivalence_check as G           # noqa: E402
import lec_gate_netlist_select as S         # noqa: E402
import phase3_one_shot_runner as P3         # noqa: E402

PLACEHOLDER = "chip_top"        # the runner's --top-name default
CORE = "core"                   # the only module the design's RTL declares
SYNTH = "phase2/stage2/synth"
ROUTED = f"{SYNTH}/{CORE}_synth.v"
PHANTOM = f"{SYNTH}/{PLACEHOLDER}_synth.v"

_CORE_RTL = ("module core(input clk, input a, input b, output reg y);\n"
             "  always @(posedge clk) y <= ~(a & b);\nendmodule\n")
_CORE_MAPPED = ("module core(clk, a, b, y);\n  input clk; input a; input b; "
                "output y;\n  wire n;\n  lib__nand2_1 g1 (.A(a), .B(b), "
                ".ZN(n));\n  lib__dffq_1 r (.CLK(clk), .D(n), .Q(y));\n"
                "endmodule\n")
# A DIE's pad ring wrapper is generated by phase 3 next to the layout, never
# staged in rtl/ and never synthesised -- it must not become step 13's subject.
_PAD_WRAPPER = ("module chip_top(input clk, input a, input b, output y);\n"
                "  core u_core(.clk(clk), .a(a), .b(b), .y(y));\nendmodule\n")


def _sha(p: Path) -> str:
    return "sha256:" + hashlib.sha256(p.read_bytes()).hexdigest()


def _tree(tmp_path: Path, *, mapped: bool = True,
          rtl_extra: dict | None = None) -> Path:
    p = tmp_path / "proj"
    rtl = p / "phase2/stage1/rtl"
    rtl.mkdir(parents=True)
    (rtl / "core.v").write_text(_CORE_RTL)
    for name, text in (rtl_extra or {}).items():
        (rtl / name).write_text(text)
    (p / SYNTH).mkdir(parents=True)
    (p / f"{SYNTH}/netlist.v").write_text("module core(); endmodule\n")
    if mapped:
        (p / ROUTED).write_text(_CORE_MAPPED)
    pnr = p / "phase3/stage3/pnr"
    pnr.mkdir(parents=True)
    (pnr / "chip_top_io.v").write_text(_PAD_WRAPPER)
    return p


@pytest.fixture()
def lec_runs(monkeypatch):
    seen: list = []

    def _run(argv, *a, **k):
        argv = [str(x) for x in argv]
        if len(argv) > 1 and argv[1].endswith("lec_run.py"):
            seen.append(argv)
            proj = Path(argv[2])
            gate = argv[argv.index("--gate-netlist") + 1]
            top = argv[argv.index("--top") + 1]
            doc = {"verdict": "PASS", "equivalent": True,
                   "compared_points": 1, "non_equivalent_points": 0,
                   "unproven_points": 0, "gold": f"{top} (RTL)",
                   "gate": f"{Path(gate).name} (synth)",
                   "proof_identity": {"top": top, "gate_netlist": {
                       "path": gate, "sha256": _sha(proj / gate)}}}
            (proj / "reports").mkdir(exist_ok=True)
            (proj / "reports/lec.json").write_text(json.dumps(doc))
            (proj / "reports/lec.rpt").write_text(
                "Equivalence successfully proven!\nProved 1 $equiv cells.\n")
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    monkeypatch.setattr(R.subprocess, "run", _run)
    return seen


def _arg(argv, flag):
    return argv[argv.index(flag) + 1]


# --------------------------------------------------------------------------- #
# the subject
# --------------------------------------------------------------------------- #
def test_placeholder_top_resolves_to_the_file_step15_routes(tmp_path):
    proj = _tree(tmp_path)
    gate, note, is_scan = S.lec_subject_for_step13(proj, PLACEHOLDER)
    assert gate == ROUTED, (gate, note)
    assert is_scan is False


def test_subject_is_what_phase3_main_hands_step_pnr(tmp_path):
    """Parity with the resolution phase 3 main applies before step_pnr."""
    proj = _tree(tmp_path)
    routed_top = CSR.effective_top(proj, PLACEHOLDER)
    assert routed_top == CORE
    assert (proj / S.lec_subject_for_step13(proj, PLACEHOLDER)[0]
            == P3.pnr_input_netlist(proj, routed_top)[0])


def test_a_real_chip_top_module_is_kept(tmp_path):
    """A design that DOES stage a chip_top module builds chip_top: unchanged."""
    proj = _tree(tmp_path, rtl_extra={"chip_top.v": _PAD_WRAPPER})
    assert S.lec_subject_for_step13(proj, PLACEHOLDER)[0] == PHANTOM


def test_an_asic_variant_is_the_routed_top(tmp_path):
    """`<top>_asic.sv` beside `<top>` is what phase 3 synthesises and routes."""
    proj = _tree(tmp_path, rtl_extra={
        "chip_top.v": _PAD_WRAPPER,
        "chip_top_asic.sv": _PAD_WRAPPER.replace("chip_top", "chip_top_asic")})
    assert (S.lec_subject_for_step13(proj, PLACEHOLDER)[0]
            == f"{SYNTH}/chip_top_asic_synth.v")


# --------------------------------------------------------------------------- #
# the producer invocation and its receipt
# --------------------------------------------------------------------------- #
def test_phase2_step13_proves_the_routed_file_under_the_placeholder(
        tmp_path, lec_runs):
    proj = _tree(tmp_path)
    rows = R.step_lec_equivalence(proj, PLACEHOLDER, "")
    (argv,) = lec_runs
    assert _arg(argv, "--gate-netlist") == ROUTED
    assert _arg(argv, "--top") == CORE
    assert rows[-1].name == "lec_equivalence"
    assert rows[-1].status == "PASS", rows[-1].detail
    rec = json.loads((proj / "reports/lec.json").read_text())
    assert rec["proof_identity"]["gate_netlist"] == {
        "path": ROUTED, "sha256": _sha(proj / ROUTED)}


def test_the_chain_hands_step13_the_routed_file(tmp_path, lec_runs):
    proj = _tree(tmp_path)
    rows = R.step_dft_lec_chain(proj, PLACEHOLDER, "", "digital_cmd_driven",
                                full_chip=False)
    assert [_arg(a, "--gate-netlist") for a in lec_runs] == [ROUTED]
    assert rows[-1].name == "lec_equivalence"


def test_before_synthesis_the_row_names_the_real_file_not_a_phantom(
        tmp_path, lec_runs):
    proj = _tree(tmp_path, mapped=False)
    rows = R.step_lec_equivalence(proj, PLACEHOLDER, "")
    assert lec_runs == []
    row = rows[-1]
    assert row.status == "NOT_MEASURED"
    assert row.reason_class == R._V.ReasonClass.INPUT_ABSENT
    assert ROUTED in row.detail
    assert PHANTOM not in row.detail
    marker = json.loads((proj / "reports/lec_not_run.json").read_text())
    assert ROUTED in marker["reason"] and PHANTOM not in marker["reason"]


# --------------------------------------------------------------------------- #
# the binding the gate and phase 3 read
# --------------------------------------------------------------------------- #
def test_binding_under_the_placeholder_matches_the_routed_file(tmp_path,
                                                               lec_runs):
    proj = _tree(tmp_path)
    R.step_lec_equivalence(proj, PLACEHOLDER, "")
    doc = json.loads((proj / "reports/lec.json").read_text())
    b = S.proof_subject_binding(proj, doc, PLACEHOLDER)
    assert b["state"] == S.BINDING_MATCH, b
    assert b["consumer_path"] == ROUTED
    rc = G.main([str(proj), "--json", str(proj / "reports/gate.json")])
    assert rc == 0
    # phase 3 finds the proof current and does not re-prove it
    assert P3.run_step13_lec_on_pnr_input(proj, CORE, "") == []
    assert len(lec_runs) == 1
